export const classesInfo = [
    {
        id: 123456,
        supervisor: "John Doe",
        capacity: 20,
        grade: 4,
        class: "4C",
    },
    {
        id: 113456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 5,
        class: "5A",
    },
    {
        id: 223456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 2,
        class: "2B",
    },
    {
        id: 233456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 1,
        class: "1C",
    },
    {
        id: 234456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 4,
        class: "4A",
    },
    {
        id: 233556,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 3,
        class: "3B",
    },
    {
        id: 233466,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 2,
        class: "2C",
    },
    {
        id: 133456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 3,
        class: "3A",
    },
    {
        id: 134456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 1,
        class: "1A",
    },
    {
        id: 153456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 1,
        class: "1B",
    },
    {
        id: 163456,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 3,
        class: "3A",
    },
    {
        id: 133455,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 4,
        class: "4B",
    },
    {
        id: 133454,
        supervisor: "John Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 5,
        class: "5C",
    },
    {
        id: 133453,
        supervisor: "Johan Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 2,
        class: "2B",
    },
    {
        id: 133452,
        supervisor: "Johana Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 2,
        class: "2C",
    },
    {
        id: 133451,
        supervisor: "Joan Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 4,
        class: "4C",
    },
    {
        id: 133450,
        supervisor: "Jill Doe",
        email: "johndoe@gmail.com",
        capacity: 20,
        grade: 1,
        class: "1A",
    },
]