export const studentsInfo = [
    {
        id: 123456,
        firstName: "John",
        lastName: "Doe",
        email: "johndoe@gmail.com",
        subjects: "Maths",
        grade: 4,
        classe: "4B",
        phone: 123456789,
        parents: "Johan Doe",
        address: "123 Main St., Brooklyn, USA",
        birthday: "2018-08-12",
        about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
        parentFirstName: "Janet",
        parentLastName: "Doe"
        // details: [
        //     {attendance: "90%"},
        //     {branches: 2},
        //     {lessons: 6},
        //     {class: 6},
        //     {at: "Attendance"},
        //     {br: "Branches"},
        //     {les: "Lessons"},
        //     {cl: 6}
        // ]
    },
    // {
    //     id: 113456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 5,
    //     class: "5A",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 223456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 2,
    //     class: "2B",
    //     phone: 123456789,
    //     parents: ["Johana Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 233456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 1,
    //     class: "1C",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 234456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 4,
    //     class: "4A",
    //     phone: 123456789,
    //     parents: ["Johana Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 233556,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 3,
    //     class: "3B",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 233466,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 2,
    //     class: "2C",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 3,
    //     class: "3A",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 134456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 1,
    //     class: "1A",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 153456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 1,
    //     class: "1B",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 163456,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 3,
    //     class: "3A",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133455,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 4,
    //     class: "4B",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133454,
    //     name: "John Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 5,
    //     class: "5C",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133453,
    //     name: "Johan Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 2,
    //     class: "2B",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133452,
    //     name: "Johana Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 2,
    //     class: "2C",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133451,
    //     name: "Joan Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 4,
    //     class: "4C",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
    // {
    //     id: 133450,
    //     name: "Jill Doe",
    //     email: "johndoe@gmail.com",
    //     subjects: ["Maths", "Physics"],
    //     grade: 1,
    //     class: "1A",
    //     phone: 123456789,
    //     parents: ["Johan Doe"],
    //     address: "123 Main St., Brooklyn, USA",
    //     about: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium veritatis.",
    //     details: [
    //         {attendance: "90%"},
    //         {branches: 2},
    //         {lessons: 6},
    //         {class: 6},
    //         {at: "Attendance"},
    //         {br: "Branches"},
    //         {les: "Lessons"},
    //         {cl: 6}
    //     ]
    // },
]